### ISSUE TITLE
Reports file not found, but

### ISSUE THREAD

**Issue by artelse** [jamescherti/compile-angel.el#1]
Installed your package and it seems to work fine.
However, in the `*Messages*` buffer, it reports it cannot find a file which lives in a lisp folder for my custom functions. The folder is set on `load-path` and all files in there are byte compiled _and_ also natively compiled. The path it reports is just the filename prefixed with my home folder, not the emacs directory.

**Comment by jamescherti** [comment]
Thank you for submitting an issue report. Your input will help improve `compile-angel` for the specific case that caused this issue in your configuration.
 
 Could you please:
 
 1. Add the following to your Emacs configuration **before** calling `(compile-angel-on-load-mode)`:
     ```elisp
     (setq compile-angel-debug t)
     ```

     Here is an example:
     ```elisp
     (use-package compile-angel
       :ensure t
       :demand t
       :config
       (setq compile-angel-debug t)
       (compile-angel-on-load-mode)
       (add-hook 'emacs-lisp-mode-hook #'compile-angel-on-save-local-mode))
       ```

2. Restart Emacs.
 
3. Then:  
    - Send me the lines related to the files that fail to compile from the buffer: `*compile-angel:debug*`.  
    - Send me the lines you are using to add custom paths to the `load-path` (e.g., `(push "the-path" load-path)`).

**Comment by artelse** [comment]
Alright.
This is reported in `*messages*` as a warning:
```
[compile-angel] Warning: The file does not exist: /home/artelse/ae-org-link-copy.el
Loading /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el (source)...done
```
and this in `*compile-angel:debug*`:
```
LOAD: /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el (string)
COMPILATION ARGS: /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el | nil
Byte and Native compilation: /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el
Start: Byte-compilation: /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el -> /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.elc
Byte-compilation Ignored (up-to-date): /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el
Native-compilation ignored (Reason: JIT compilation will do it): /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el
compile-angel--hook-after-load-functions: /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el
compile-angel--hook-after-load-functions: COMPILE: /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el
COMPILATION ARGS: /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el | nil
SKIP (In the skip hash list): /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el | nil
SKIP (Does not need compilation): /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el | nil
```
And `load-path` config:
`(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))`

I moved it to before `compile-angel` package definition, but this didn't resolve the issue.

**Comment by jamescherti** [comment]
1. Does the file `/home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.elc` exist?

Could you send me the output of the following command?
```
ls -l /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.elc /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.elc
```

(I would like to verify if the file is up to date.)

2. Could you also try the [latest version of `compile-angel` from the Git repository](https://github.com/jamescherti/compile-angel.el/) (main branch)? I just pushed some updates that might fix the issue.

**Comment by artelse** [comment]
1. yes
```
-rw-rw-r-- 1 artelse artelse 901 Nov 24 14:12 /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.elc
-rw-rw-r-- 1 artelse artelse 901 Nov 24 14:12 /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.elc
```
2. done
The update resolves the issue:
`Loading /home/artelse/.config/emacs/aemacs/lisp/ae-org-link-copy.el (source)...done`
3. I have a function that loads all the files in the `lisp` directory that uses `load-file` with a full path.

Great thanks!

**Comment by jamescherti** [comment]
Excellent! Thank you for confirming that the bug has been fixed.
