### ISSUE TITLE
Compiling certain files on every startup

### ISSUE THREAD

**Issue by arthsmn** [jamescherti/compile-angel.el#2]
The `*Async-native-compile-log*` always show this output:
``` log
Compiling /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/cus-load.el...
Compiling /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/theme-loaddefs.el...
Compiling /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/loaddefs.el.gz...
uncompressing loaddefs.el.gz...
uncompressing loaddefs.el.gz...done
Compiling /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/international/charprop.el...
Compiling /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/emacs-lisp/cl-loaddefs.el.gz...
uncompressing cl-loaddefs.el.gz...
uncompressing cl-loaddefs.el.gz...done
Compilation finished.
Compilation finished.
Compilation finished.
Compilation finished.
```
This compilation increases startup time and, if I hook `compile-angel-on-load-mode` in an `after-init-hook`, it freezes Emacs for a second while compiling those files.

I would like to know if it's a normal behavior or something that can be fixed. I thought about ignoring these files, but I don't know why they wouldn't be (byte/native)-compiled.

Edit:
With this config:
``` emacs-lisp
(leaf compile-angel :elpaca t
  :require t
  :custom ((compile-angel-verbose . nil)
           (native-comp-async-query-on-exit . t)
           (compile-angel-excluded-files-regexps . '(
                                                     "\\cus-load\\.el$"
                                                     "\\theme-loaddefs\\.el$"
                                                     "\\loaddefs\\.el.gz$"
                                                     "\\charprop\\.el$"
                                                     "\\cl-loaddefs\\.el.gz$"
                                                     )))
  :hook (emacs-lisp-mode-hook . compile-angel-on-save-local-mode)
  :defer-config (compile-angel-on-load-mode))
```
The files `cua-load.el` and `charprop.el` get compiled even though they are in the excluded list.

**Comment by jamescherti** [comment]
Hello @arthsmn,

Try the following regular expressions instead:
```elisp
(compile-angel-excluded-files-regexps . '("/cus-load\\.el$"
                                          "/theme-loaddefs\\.el$"
                                          "/loaddefs\\.el\\.gz$"
                                          "/charprop\\.el$"
                                          "/cl-loaddefs\\.el\\.gz$")
```

**Comment by arthsmn** [comment]
> Hello @arthsmn,
> 
> Try the following regular expressions instead:
> 
> ```emacs-lisp
> (compile-angel-excluded-files-regexps . '("/cus-load\\.el$"
>                                           "/theme-loaddefs\\.el$"
>                                           "/loaddefs\\.el\\.gz$"
>                                           "/charprop\\.el$"
>                                           "/cl-loaddefs\\.el\\.gz$")
> ```

Thanks, this fixes the problem! Do you know why these files are being recompiled at every startup? They aren't changing, `/nix/store` is immutable.

**Comment by jamescherti** [comment]
Those files are not intended to be compiled. They are being recompiled at every startup due to previous compilation failures.

I am considering whether `compile-angel` should always ignore loaddefs files. I will look for a reliable method to detect whether a file is a loaddef file.

**Comment by arthsmn** [comment]
> Those files are not intended to be compiled. They are being recompiled at every startup due to previous compilation failures.
> 
> I am considering whether `compile-angel` should always ignore loaddefs files. I will look for a reliable method to detect whether a file is a loaddef file.

Thanks for the explanation!

**Comment by jamescherti** [comment]
> Thanks for the explanation!

My pleasure, @arthsmn!

**Comment by jamescherti** [comment]
I have just committed a change to the `develop` branch that addresses this issue.

Would you mind removing the regular expressions and testing the `develop` branch (which ignores loaddefs by default)?

Thanks!

**Comment by jamescherti** [comment]
I recommend that you enable debugging while testing the `develop` branch by setting:

```emacs-lisp
(setq compile-angel-debug t)
```

This will allow you to view detailed information about what `compile-angel` is doing in the `*compile-angel:debug*` buffer.

**Comment by arthsmn** [comment]
> I have just committed a change to the `develop` branch that addresses this issue.
> 
> Would you mind removing the regular expressions in `compile-angel-excluded-files-regexps` and testing the `develop` branch (which ignores loaddefs by default)?
> 
> Thanks!

This solves the issues for the loaddefs, but charprop is still being compiled every time.

**Comment by jamescherti** [comment]
I canceled the commit pushed to the develop branch. For now, it seems better to let users exclude load definitions manually using regular expressions until a more suitable solution is identified. I may consider adding them as default values to `compile-angel-excluded-files-regexps`. Thank you, @arthsmn, for your feedback as always.

**Comment by arthsmn** [comment]
> I canceled the commit pushed to the develop branch. For now, it seems better to let users exclude load definitions manually using regular expressions until a more suitable solution is identified. I may consider adding them as default values to `compile-angel-excluded-files-regexps`. Thank you, @arthsmn, for your feedback as always.

Ok, thanks for the help!

**Comment by arthsmn** [comment]
@jamescherti sorry to bother again, but there's one file being excluded in the regexps that is being recompiled every time. Here's the compile-angel log for the relevant file:
```log
LOAD: /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/org/org-loaddefs (string)
COMPILATION ARGS: /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/org/org-loaddefs.el.gz | nil
SKIP (.el file excluded with a regex): /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/org/org-loaddefs.el.gz
SKIP (Does not need compilation): /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/org/org-loaddefs.el.gz | nil
```
But the buffer `*Async-native-compile-log*` shows this:
```log
Compiling /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/org/org-loaddefs.el.gz...
uncompressing org-loaddefs.el.gz...
uncompressing org-loaddefs.el.gz...done
Compilation finished.
```

**Comment by jamescherti** [comment]
This is not an issue with compile-angel.

Compile-angel skipped the file due to the regular expression:

```
SKIP (.el file excluded with a regex): /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/org/org-loaddefs.el.gz
SKIP (Does not need compilation): /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/org/org-loaddefs.el.gz | nil
```

However, another process compiled the file:

```
Compiling /nix/store/laalwa0p76k3vqc4z7hvdjgir47ncgl8-emacs-pgtk-30.0.92/share/emacs/30.0.92/lisp/org/org-loaddefs.el.gz...
uncompressing org-loaddefs.el.gz...
uncompressing org-loaddefs.el.gz...done
Compilation finished.
```

**Comment by jamescherti** [comment]
In case you're interested in trying a new feature that may help address this issue, I have added a new setting to the develop branch: `compile-angel-excluded-path-suffixes`. This allows you to specify a list of path suffixes.

For example:
```emacs-lisp
(setq compile-angel-excluded-path-suffixes '("loaddefs.el" "/cus-load.el" "charprop.el"))
```

If a path suffix in `compile-angel-excluded-path-suffixes` ends with `.el`, compile-angel will automatically exclude the `.el.gz` variant of that file as well (e.g., `loaddefs.el` will also exclude `loaddefs.el.gz`).

This will be merged into the master branch in a few hours. Please let me know if you have any comments.

**Comment by arthsmn** [comment]
> In case you're interested in trying a new feature that may help address this issue, I have added a new setting to the develop branch: `compile-angel-excluded-files`. This allows you to specify a list of path suffixes.
> 
> For example:
> 
> ```emacs-lisp
> (setq compile-angel-excluded-files '("loaddefs.el" "/cus-load.el" "charprop.el"))
> ```
> 
> If a path suffix in `compile-angel-excluded-files` ends with `.el`, compile-angel will automatically exclude the `.el.gz` variant of that file as well (e.g., `loaddefs.el` will also exclude `loaddefs.el.gz`).
> 
> This will be merged into the master branch in a few hours. Please let me know if you have any comments.
> 
> EDIT: I have changed the variables name. The variable name may change before it is merged into the master branch.

This worked like a charm! Also, way better to declare stuff, really good idea!

**Comment by jamescherti** [comment]
Thank you for your feedback and for being the first to try this new feature!

I have just merged it into the main branch.

**Comment by arthsmn** [comment]
> Thank you for your feedback and for being the first to try this new feature!
> 
> I have just merged it into the main branch.

No problem, glad to help!
